### PR TITLE
Modified CamClay update

### PR DESCRIPTION
**Pull request by nagelt**
This an updated version corresponding to the standard formulation. Updated documentation will follow (we'll prepare a technical note on some algorithmic aspects and parameter clarification).

### CODE REVIEW

**Comment by nagelt** [comment]
@thelfer As I understood it, we should keep the 2020 version, although it may no longer be necessary?

**Comment by thelfer** [comment]
> @thelfer As I understood it, we should keep the 2020 version, although it may no longer be necessary?

That what I would do it the behaviour was used in critical safety studies. That would allow future engineers to measure the impacts of the change on their results.

**Comment by thelfer** [comment]
> This an updated version corresponding to the standard formulation. Updated documentation will follow (we'll prepare a technical note on some algorithmic aspects and parameter clarification).

Do you mind if the PR is kept open up to the documentation update ?

BTW, one shall also keep the documentation for the 2020 version !

**Comment by nagelt** [comment]
No, I don't mind. Just wanted to start preparing this while I had some time.

**Pull request merged**
